### ISSUE TITLE
#include <uv.h>

### ISSUE THREAD

**Issue by aishuidedabai** [ShadowsocksR-Live/shadowsocksr-libev#1]
#include <uv.h> 不存在

**Comment by ssrlive** [comment]
正在改寫. 目前是 https://github.com/ShadowsocksR-Live/shadowsocksr-libev/commit/e560138e7392fec6ad7fd6904a30e2e91b4e9fa8 可以編譯. 編譯之前必須取下個各子模塊和子子模塊.

**Comment by aishuidedabai** [comment]
我想请问您在改的什么，我看到了很多内存释放的重写，您最终想做什么

**Comment by ralphshane** [comment]
随机崩溃在 libuv 里，我没找出原因。如果你能修正这个问题，欢迎你从上述提交点开个分支提交pr。

**Comment by ssrlive** [comment]
随机崩溃在 libuv 里，我没找出原因。如果你能修正这个问题，欢迎你从上述提交点开个分支提交pr。
