### ISSUE TITLE
libcork vs 2015 release x86生成报错

### ISSUE THREAD

**Issue by 380wmda999** [ShadowsocksR-Live/shadowsocksr-libev#2]
1>------ 已启动生成: 项目: libcork, 配置: Release Win32 ------
1>  commands.c
1>..\..\libcork\cli\commands.c(211): error C2065: “__func__”: 未声明的标识符
1>  allocator.c
1>..\..\libcork\core\allocator.c(79): error C2065: “__func__”: 未声明的标识符
1>..\..\libcork\core\allocator.c(98): error C2065: “__func__”: 未声明的标识符
1>..\..\libcork\core\allocator.c(409): error C2065: “__func__”: 未声明的标识符
1>  error.c
1>..\..\libcork\core\error.c(92): warning C4047: “函数”:“volatile LONG *”与“cork_error *volatile *”的间接级别不同
1>..\..\libcork\core\error.c(92): warning C4024: “__sync_val_compare_and_swap”: 形参和实参 1 的类型不同
1>..\..\libcork\core\error.c(92): warning C4047: “函数”:“LONG”与“cork_error *”的间接级别不同
1>..\..\libcork\core\error.c(92): warning C4024: “__sync_val_compare_and_swap”: 形参和实参 2 的类型不同
1>..\..\libcork\core\error.c(92): warning C4024: “__sync_val_compare_and_swap”: 形参和实参 3 的类型不同
1>  gc.c
1>  hash.c
1>  ip-address.c
1>  mempool.c
1>  timestamp.c
1>  u128.c
1>  version.c
1>  array.c
1>  bitset.c
1>  buffer.c
1>  dllist.c
1>  file-stream.c
1>  hash-table.c
1>  managed-buffer.c
1>  ring-buffer.c
1>  slice.c
1>  env.c
1>  正在编译...
1>  exec.c
1>  thread.c
========== 生成: 成功 0 个，失败 1 个，最新 1 个，跳过 0 个 ==========

严重性	代码	说明	项目	文件	行	源
错误(活动)		未定义标识符 "cork_hash_f"	libcork	d:\shadowsocksr-libev\libcork\include\libcork\ds\hash-table.h	55	Intellisense
错误(活动)		未定义标识符 "cork_copy_f"	libcork	d:\shadowsocksr-libev\libcork\include\libcork\ds\array.h	80	Intellisense
错误(活动)		变量 "inline" 不是类型名	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\timestamp.h	62	Intellisense
错误(活动)		应输入“;”	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\timestamp.h	63	Intellisense
错误(活动)		应输入“;”	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\hash.h	323	Intellisense
错误	C2065	“__func__”: 未声明的标识符	libcork	D:\shadowsocksr-libev\libcork\cli\commands.c	211	生成
错误	C2065	“__func__”: 未声明的标识符	libcork	D:\shadowsocksr-libev\libcork\core\allocator.c	79	生成
错误	C2065	“__func__”: 未声明的标识符	libcork	D:\shadowsocksr-libev\libcork\core\allocator.c	98	生成
错误	C2065	“__func__”: 未声明的标识符	libcork	D:\shadowsocksr-libev\libcork\core\allocator.c	409	生成
错误(活动)		应输入“;”	libcork	d:\shadowsocksr-libev\libcork\include\libcork\config\mingw32.h	43	Intellisense
错误(活动)		应输入类型说明符	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\callbacks.h	27	Intellisense
错误(活动)		不允许使用返回函数的函数	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\callbacks.h	27	Intellisense
错误(活动)		变量 "uint32_t" 不是类型名	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\error.h	24	Intellisense
错误(活动)		变量 "uint32_t" 不是类型名	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\error.h	67	Intellisense
错误(活动)		变量 "uint32_t" 不是类型名	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\hash.h	26	Intellisense
错误(活动)		变量 "inline" 不是类型名	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\hash.h	46	Intellisense
错误(活动)		应输入“;”	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\hash.h	47	Intellisense
错误(活动)		变量 "inline" 不是类型名	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\hash.h	75	Intellisense
错误(活动)		应输入“;”	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\hash.h	77	Intellisense
错误(活动)		表达式必须含有常量值	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\hash.h	101	Intellisense
错误(活动)		表达式必须含有常量值	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\hash.h	102	Intellisense
错误(活动)		应输入声明	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\hash.h	103	Intellisense
错误(活动)		应输入“;”	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\hash.h	114	Intellisense
错误(活动)		常量表达式中不允许函数调用	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\hash.h	115	Intellisense
错误(活动)		应输入声明	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\hash.h	116	Intellisense
错误(活动)		应输入声明	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\hash.h	117	Intellisense
错误(活动)		变量 "inline" 不是类型名	libcork	d:\shadowsocksr-libev\libcork\include\libcork\core\hash.h	321	Intellisense

后面的错误 好像是我这个编译器不支持inline  去掉就好了 但是 前面4个 未定义的表示符 实在没找到哪里的问题 求助

**Comment by ssrlive** [comment]
自己看文檔再檢查. 不要一出錯就叫喚

**Comment by 380wmda999** [comment]
哪有有文档呢  依旧是之前的错误
1>------ 已启动全部重新生成: 项目: pthreads, 配置: Release Win32 ------
1>  pthread.c
1>    正在创建库 D:\shadowsocksr-libev\win32\Release\pthreads.lib 和对象 D:\shadowsocksr-libev\win32\Release\pthreads.exp
1>  正在生成代码
1>  All 188 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
1>  已完成代码的生成
1>  pthreads.vcxproj -> D:\shadowsocksr-libev\win32\Release\pthreads.dll
2>------ 已启动全部重新生成: 项目: libcork, 配置: Release Win32 ------
2>  commands.c
2>..\..\libcork\cli\commands.c(211): error C2065: “__func__”: 未声明的标识符
2>  allocator.c
2>..\..\libcork\core\allocator.c(79): error C2065: “__func__”: 未声明的标识符
2>..\..\libcork\core\allocator.c(98): error C2065: “__func__”: 未声明的标识符
2>..\..\libcork\core\allocator.c(409): error C2065: “__func__”: 未声明的标识符
2>  error.c
2>..\..\libcork\core\error.c(92): warning C4047: “函数”:“volatile LONG *”与“cork_error *volatile *”的间接级别不同
2>..\..\libcork\core\error.c(92): warning C4024: “__sync_val_compare_and_swap”: 形参和实参 1 的类型不同
2>..\..\libcork\core\error.c(92): warning C4047: “函数”:“LONG”与“cork_error *”的间接级别不同
2>..\..\libcork\core\error.c(92): warning C4024: “__sync_val_compare_and_swap”: 形参和实参 2 的类型不同
2>..\..\libcork\core\error.c(92): warning C4024: “__sync_val_compare_and_swap”: 形参和实参 3 的类型不同
2>  gc.c
2>  hash.c
2>  ip-address.c
2>  mempool.c
2>  timestamp.c
2>  u128.c
2>  version.c
2>  array.c
2>  bitset.c
2>  buffer.c
2>  dllist.c
2>  file-stream.c
2>  hash-table.c
2>  managed-buffer.c
2>  ring-buffer.c
2>  slice.c
2>  env.c
2>  正在编译...
2>  exec.c
2>  thread.c
========== 全部重新生成: 成功 1 个，失败 1 个，跳过 0 个 ==========

**Comment by 380wmda999** [comment]
就是 cork_unreachable  cork_abort  这两个函数报错的

**Comment by ssrlive** [comment]
你就不會把頭文件的搜索路徑自己加入到工程裡嗎? 弄好了提交一個PR給我.

**Comment by 380wmda999** [comment]
是 頭文件的搜索路徑 的问题？  我改了附加包含目录 也一样的 
计算的值 
D:\shadowsocksr-libev\win32\libcork\../../libcork/include
D:\shadowsocksr-libev\win32\libcork\include
D:\shadowsocksr-libev\win32\libcork\../../depends/pthreads4w/code
%(AdditionalIncludeDirectories)
也不行 没懂你的意思

**Comment by 380wmda999** [comment]
而且 如果是头文件 没有找到的话  也是会有提示的啊 没有这个提示

**Comment by ssrlive** [comment]
D:\shadowsocksr-libev\win32\libcork**/**../../libcork/include

**Comment by ssrlive** [comment]
少了一個斜杠. 媽的漢化版的VS2015就這個德性?

**Comment by ssrlive** [comment]
年輕人比我這七老八十的人眼神還不好使?

**Comment by 380wmda999** [comment]
不是 没有少斜杠  那里是有一个 反斜杠 的 但是 这个 被这个编辑器给去掉了

**Comment by ssrlive** [comment]
我現在是這個樣子. 很好使. 
C:\Users\Administrator\Desktop\shadowsocksr-libev\win32\libcork\/../../libcork/include
C:\Users\Administrator\Desktop\shadowsocksr-libev\win32\libcork\/include
C:\Users\Administrator\Desktop\shadowsocksr-libev\win32\libcork\/../../depends/pthreads4w/code
%(AdditionalIncludeDirectories)

**Comment by 380wmda999** [comment]
改了 
原始的 
$(ProjectDir)/../../libcork/include
$(ProjectDir)/include
$(ProjectDir)/../../depends/pthreads4w/code
计算的值
D:\shadowsocksr-libev\win32\libcork\/../../libcork/include
D:\shadowsocksr-libev\win32\libcork\/include
D:\shadowsocksr-libev\win32\libcork\/../../depends/pthreads4w/code
%(AdditionalIncludeDirectories)

还是一样的 错误
真的不是这个的问题

**Comment by ssrlive** [comment]
一個編譯警告去掉了. 取最新的提交看看.

**Comment by 380wmda999** [comment]
还是 一样的错误 警告是没有了 

>------ 已启动全部重新生成: 项目: pthreads, 配置: Release Win32 ------
1>  pthread.c
1>    正在创建库 D:\shadowsocksr-libev\win32\Release\pthreads.lib 和对象 D:\shadowsocksr-libev\win32\Release\pthreads.exp
1>  正在生成代码
1>  All 186 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
1>  已完成代码的生成
1>  pthreads.vcxproj -> D:\shadowsocksr-libev\win32\Release\pthreads.dll
2>------ 已启动全部重新生成: 项目: libcork, 配置: Release Win32 ------
2>  commands.c
2>..\..\libcork\cli\commands.c(211): error C2065: “__func__”: 未声明的标识符
2>  allocator.c
2>..\..\libcork\core\allocator.c(79): error C2065: “__func__”: 未声明的标识符
2>..\..\libcork\core\allocator.c(98): error C2065: “__func__”: 未声明的标识符
2>..\..\libcork\core\allocator.c(409): error C2065: “__func__”: 未声明的标识符
2>  error.c
2>  gc.c
2>  hash.c
2>  ip-address.c
2>  mempool.c
2>  timestamp.c
2>  u128.c
2>  version.c
2>  array.c
2>  bitset.c
2>  buffer.c
2>  dllist.c
2>  file-stream.c
2>  hash-table.c
2>  managed-buffer.c
2>  ring-buffer.c
2>  slice.c
2>  env.c
2>  正在编译...
2>  exec.c
2>  thread.c
========== 全部重新生成: 成功 1 个，失败 1 个，跳过 0 个 ==========

**Comment by 380wmda999** [comment]
追过去 就是 cork_unreachable   和 cork_abort 这两个函数

**Comment by ssrlive** [comment]
為了通過編譯, 你臨時把硬路徑寫到代碼裡再說. 反正以後也沒人動這個垃圾庫.

**Comment by 380wmda999** [comment]
应该不是 文件 没有找到吧 如果是文件没有找到 编译的时候 会有提示 无法打开头文件的

**Comment by ssrlive** [comment]
刪掉整個代碼. 重新取個新的看看.

**Comment by ssrlive** [comment]
為了通過編譯. 直接把 cork_unreachable 和 cork_abort  改成 assert(false) 和 abort() 得了.

**Comment by 380wmda999** [comment]
正在重新拉取代码 如果还是不行 我就这样做

**Comment by 380wmda999** [comment]
额 编译出来了 但是 我发现 编译出来的 根本不能用 一直 timeout   为啥？
[win32.zip](https://github.com/ShadowsocksR-Live/shadowsocksr-libev/files/1443526/win32.zip)

**Comment by ssrlive** [comment]
因为几天前创建的 client 文件夹开始了新的工作。你想要旧代码跑起来，得把新的去掉，把旧的加回去。

**Comment by 380wmda999** [comment]
应该怎么弄呢?  还有就是 没看懂你在弄什么 就是  用libuv 重写 ssr的client么

**Comment by ssrlive** [comment]
是。因为直接从 疯眼汉 和 破娃酱 的代码移除 libev 添加 libuv，会不定时地随机崩溃在某个地方，有时是 malloc 有时是 libuv
里。我花了大量时间无法排除故障。就只能从头开始。 始于我个人的 s5proxy 工程。

**Comment by 380wmda999** [comment]
我现在用的是 ss-local 就是 ssr windows 上面编译出来的那个 这个 相比 原来那个 会更快？

**Comment by ssrlive** [comment]
一看到 mingw 就就心理不舒服，从来没有碰过。

**Comment by 380wmda999** [comment]
额 好吧 我怎么把旧的加回去呢  现在这个跑步起来 我想看看速度怎么样

**Comment by ssrlive** [comment]
取新的吧. 加了一個工程 ssr-old.

**Comment by 380wmda999** [comment]
好的 谢谢

**Comment by ssrlive** [comment]
已經將舊版的隨機崩潰修正了. 現在舊版是堅如磐石, 穩如泰山. 內存佔用僅為 7 M, 火力全開時內存佔用 27 M. 關閉瀏覽器後內存馬上降為 7 M. 歡迎擴散. 歡迎集成. 歡迎移植. 目前幾乎適用於所有已知平台.

**Comment by 380wmda999** [comment]
好的 我试试看
